[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  branch = "master"
  name = "github.com/Nik-U/pbc"

[[constraint]]
  branch = "master"
  name = "github.com/dchest/wots"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"
